name: CI Workflow
on:  
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Run linter
      run: yarn run lint

    - name: Run unit tests
      run: yarn test:unit --coverage
  deploy:
    name: Deploy on github pages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up shell
      uses: actions/setup-shell@v2
      with:
        shell: bash
    - name: Run script
      run: sh deploy.sh

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
    
  #   - name: Checkout
  #     uses: actions/checkout@v1

  #   - name: Build
  #     run: |
  #       npm install
  #       npm run-script build
  #     env:
  #       VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
  #       VITE_AUTH_CLIENT_ID: ${{ secrets.VITE_AUTH_CLIENT_ID }}
  #       VITE_AUTH_REDIRECT_URL: ${{ secrets.VITE_AUTH_REDIRECT_URL }}
  #       VITE_API_AUDIENCE: ${{ secrets.VITE_API_AUDIENCE }}
  #       VITE_MOCK_API_URL: ${{ secrets.VITE_MOCK_API_URL }}

  #   - name: Deploy
  #     uses: Sigma-vue-internship/easy-interview
  #     with:
  #       GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  #       BRANCH: develop
  #       FOLDER: dist